# TODO: mount transcode dir from host
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "plex"
  namespace: "plex"
  labels:
    app.kubernetes.io/name: "plex"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "plex"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "plex"
        app.kubernetes.io/component: "server"
    spec:
      containers:
        - name: "plex"
          image: "docker.io/plexinc/pms-docker:latest"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "TZ"
              value: "Europe/Oslo"
            - name: "PLEX_UID"
              value: "1000"
            - name: "PLEX_GID"
              value: "1000"
            - name: "CHANGE_CONFIG_DIR_OWNERSHIP"
              value: "false"
            - name: "ALLOWED_NETWORKS"
              value: "192.168.1.0/24"
          ports:
            - containerPort: 32400
              protocol: "TCP"
            - containerPort: 3005
              protocol: "TCP"
            - containerPort: 8324
              protocol: "TCP"
            - containerPort: 32469
              protocol: "TCP"
            - containerPort: 1900
              protocol: "UDP"
            - containerPort: 32410
              protocol: "UDP"
            - containerPort: 32412
              protocol: "UDP"
            - containerPort: 32413
              protocol: "UDP"
            - containerPort: 32414
              protocol: "UDP"
          startupProbe:
            tcpSocket:
              port: 32400
          readinessProbe:
            tcpSocket:
              port: 32400
          livenessProbe:
            tcpSocket:
              port: 32400
          resources: { }
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/media"
              name: "media"
            - mountPath: "/dev/dri"
              name: "dri"
      volumes:
        - name: "config"
          hostPath:
            path: "/pool/services/plex2"
        - name: "media"
          hostPath:
            path: "/pool/media"
        - name: "dri"
          hostPath:
            path: "/dev/dri"
