---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "plex-tmp"
  namespace: "plex"
spec:
  hostPath:
    path: "/tmp"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  persistentVolumeReclaimPolicy: "Retain"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "plex-tmp"
    namespace: "plex"
  capacity:
    storage: "200Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "plex-config"
  namespace: "plex"
spec:
  hostPath:
    path: "/pool/services/plex2"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  persistentVolumeReclaimPolicy: "Retain"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "plex-config"
    namespace: "plex"
  capacity:
    storage: "15Ti"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "plex-media"
  namespace: "plex"
spec:
  hostPath:
    path: "/pool/media"
  volumeMode: "Filesystem"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  persistentVolumeReclaimPolicy: "Retain"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "plex-media"
    namespace: "plex"
  capacity:
    storage: "15Ti"
