---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "plex"
  namespace: "plex"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "plex"
    app.kubernetes.io/component: "server"
  ports:
    - port: 32400
      targetPort: 32400
      protocol: "TCP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "plex-lb"
  namespace: "plex"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.53"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "plex"
    app.kubernetes.io/component: "server"
  ports:
    - port: 80
      targetPort: 32400
      protocol: "TCP"
