---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "flaresolverr"
  namespace: "flaresolverr"
  labels:
    app.kubernetes.io/name: "flaresolverr"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "flaresolverr"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "flaresolverr"
    spec:
      containers:
        - name: "flaresolverr"
          image: "ghcr.io/flaresolverr/flaresolverr:latest"
          imagePullPolicy: "Always"
          env:
            - name: "TZ"
              value: "UTC"
            - name: "LOG_LEVEL"
              value: "info"
            - name: "LOG_HTML"
              value: "false"
            - name: "TEST_URL"
              value: "https://www.google.com"
            - name: "PORT"
              value: "8191"
            - name: "PROMETHEUS_ENABLED"
              value: "false"
            - name: "PROMETHEUS_PORT"
              value: "8192"
          ports:
            - containerPort: 8191
              protocol: "TCP"
          startupProbe:
            tcpSocket:
              port: 8191
          readinessProbe:
            tcpSocket:
              port: 8191
          livenessProbe:
            tcpSocket:
              port: 8191
          resources:
            limits:
              memory: "1024Mi"
