---
apiVersion: v1
kind: Service
metadata:
  name: "flaresolverr"
  namespace: "flaresolverr"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "flaresolverr"
  ports:
    - port: 8191
      targetPort: 8191
      protocol: "TCP"
