---
apiVersion: source.toolkit.fluxcd.io/v1
kind: "GitRepository"
metadata:
  name: "gateway-api"
  namespace: "flux-system"
spec:
  interval: "24h"
  url: "https://github.com/kubernetes-sigs/gateway-api"
  ref:
    semver: "1.3.x"
---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: "Kustomization"
metadata:
  name: "gateway-api"
  namespace: "flux-system"
spec:
  interval: "24h"
  prune: false
  sourceRef:
    kind: "GitRepository"
    name: "gateway-api"
  path: "./config/crd/experimental"
  targetNamespace: "kube-system"
