---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "cilium"
  namespace: "flux-system"
spec:
  url: "https://helm.cilium.io"
  interval: "24h"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "cilium"
  namespace: "flux-system"
spec:
  interval: "24h"
  chart:
    spec:
      chart: "cilium"
      sourceRef:
        kind: "HelmRepository"
        name: "cilium"
        namespace: "flux-system"
      interval: "24h"
      version: "1.17.3"
  targetNamespace: "kube-system"
  releaseName: "cilium"
  install:
    crds: "Create"
  dependsOn: [] # TODO: gateway-api
  values:
    debug:
      enabled: false
    k8sServiceHost: "192.168.1.21"
    k8sServicePort: "6443"
    k8sClientRateLimit:
      qps: 50
      burst: 200
    rollOutCiliumPods: true
    l2announcements:
      enabled: true
    l2podAnnouncements:
      enabled: false
    cni:
      enabled: true
      uninstall: false
      exclusive: true
    ingressController:
      enabled: false
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "true"
    k8sNetworkPolicy:
      enabled: true
    externalIPs:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    kubeProxyReplacement: true
    egressGateway:
      enabled: false
    nodePort:
      enabled: false
    operator:
      enabled: true
      rollOutPods: true
      replicas: 1
