# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
# TODO: change namespace to 'cilium'?
---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "gateway-api.yaml"
  - "helm-release.yaml"
  - "ip-pool.yaml"
  - "l2-policy.yaml"
  - "service.yaml"
