---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "policy.yaml"
  - "pool.yaml"
  - "service.yaml"
helmCharts:
  - name: "cilium"
    namespace: "kube-system"
    repo: "https://helm.cilium.io"
    version: "1.17.3"
    releaseName: "cilium"
    includeCRDs: true
    valuesFile: "values.yaml"
