---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "announcement-policy.yaml"
  - "ip-pool.yaml"
helmCharts:
  - name: "cilium"
    repo: "https://helm.cilium.io"
    version: "1.17.2"
    releaseName: "cilium"
    includeCRDs: true
    namespace: "kube-system"
    valuesFile: "values.yaml"
labels:
  - pairs:
      app.kubernetes.io/managed-by: "Helm"
commonAnnotations:
  meta.helm.sh/release-name: "cilium"
  meta.helm.sh/release-namespace: "kube-system"
