---
apiVersion: "cilium.io/v2alpha1"
kind: "CiliumLoadBalancerIPPool"
metadata:
  name: "default-pool"
spec:
  blocks:
    - start: "192.168.1.50"
      stop: "192.168.1.99"
  allowFirstLastIPs: "Yes"
