---
apiVersion: v1
kind: "Service"
metadata:
  name: "hubble-ui-lb"
  namespace: "kube-system"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.51"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/part-of: cilium
  ports:
    - port: 80
      targetPort: 8081
      protocol: "TCP"
