version: "3.7"

networks:
  web:
    name: web
    external: false
  proxy:
    external: true
  docker-proxy:
    external: true

services:
  # https://hub.docker.com/r/pawelmalak/flame
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    restart: unless-stopped
    networks:
      - web
      - proxy
      - docker-proxy
    ports:
      - 5005:5005
    expose:
      - "5005"
    volumes:
      - ./config/flame:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flame.entrypoints=websecure"
      - "traefik.http.routers.flame.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.flame.middlewares=auth-middleware"
      - "traefik.http.services.flame.loadbalancer.server.port=5005"
      # flame
      - flame.type=app
      - flame.name=flame
      - flame.url=https://${DOMAIN}
      - flame.icon=fire

  # https://hub.docker.com/r/traefik/whoami
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`debug.${DOMAIN}`)"
      - "traefik.http.routers.whoami.middlewares=no-auth-middleware"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # flame
      - flame.type=app
      - flame.name=whoami
      - flame.url=https://debug.${DOMAIN}
      - flame.icon=test-tube

  # https://hub.docker.com/_/nginx
  robots:
    image: nginx:alpine
    container_name: robots
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "80"
    volumes:
      - ./config/robots/robots.txt:/usr/share/nginx/html/robots.txt:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.robots.entrypoints=websecure"
      - "traefik.http.routers.robots.rule=HostRegexp(`{host:.*}`) && Path(`/robots.txt`)"
      - "traefik.http.routers.robots.priority=99"
      - "traefik.http.routers.robots.middlewares=no-auth-middleware"
      - "traefik.http.services.robots.loadbalancer.server.port=80"