version: "3.7"

networks:
  dev:
    name: dev
    external: false
  proxy:
    external: true

services:
  # https://hub.docker.com/r/linuxserver/code-server
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    networks:
      - proxy
      - dev
    expose:
      - "8443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - HASHED_PASSWORD=${CODE_SERVER_HASHED_PASSWORD}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD}
      - SUDO_PASSWORD_HASH=${CODE_SERVER_SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=${CODE_SERVER_PROXY_DOMAIN}
    volumes:
      - ${POOL}/services/code-server:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.rule=Host(`code.${DOMAIN}`) || Host(`dev.${DOMAIN}`)"
      - "traefik.http.routers.code-server.middlewares=auth-middleware"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
      # flame
      - flame.type=app
      - flame.name=code-server
      - flame.url=https://code.${DOMAIN}
      - flame.icon=code-tags