version: "3.7"

networks:
  docker-proxy:
    name: docker-proxy
    external: false

services:
  # https://hub.docker.com/r/tecnativa/docker-socket-proxy
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    networks:
      - docker-proxy
    expose:
      - "2375"
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro