version: "3.7"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "800:80"     # port 80 is taken by host
      - "4433:443"    # port 443 is taken by host
      - "8080:8080"
    expose:
      - "80"
      - "443"
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./config/proxy/acme.json:/acme.json
    command:
      # https://doc.traefik.io/traefik/reference/static-configuration/cli/
      # global settings
      - "--global.checknewversion=true"
      - "--global.sendanonymoususage=false"
      # api settings
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # logging
      - "--log.level=DEBUG"
      - "--log.format=json"
      - "--log.filepath=traefik.log"
      # access logs
      - "--accesslog.bufferingsize=100"
      - "--accesslog.filepath=access.log"
      - "--accesslog.format=json"
      # entrypoints
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      # providers/ docker
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      # cert resolver/ acme
      - "--certificatesresolvers.http.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.http.acme.storage=acme.json"
      - "--certificatesresolvers.http.acme.httpchallenge=true"
      - "--certificatesresolvers.http.acme.httpchallenge.entrypoint=http"
    labels:
      - traefik.http.routers.traefik-http.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.traefik-http.entrypoints=http
      - traefik.http.routers.traefik-http.middlewares=redirect
      - traefik.http.routers.traefik-https.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-http.service=api@internal
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=http"

networks:
  proxy:
    name: proxy
    external: false