version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Oslo
    volumes:
      - /mnt/pool1/services/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

