version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    env_file:
      - .env.pirate
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/prowlarr:/config

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    env_file:
      - .env.pirate
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/radarr:/config
      - ${POOL}/media:/media

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    env_file:
      - .env.pirate
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/sonarr:/config
      - ${POOL}/media:/media
  
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    env_file:
      - .env.pirate
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/transmission:/config
      - ${POOL}/media:/media
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - 8080:8081  # avoid conflicts with other services running on port 8080
      - 9090:9090
    env_file:
      - .env.pirate
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/sabnzbd:/config
      - ${POOL}/media:/media