version: "3.7"
services:
  # https://hub.docker.com/r/linuxserver/plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    expose:
      - "32400"
      - "1900/udp"
      - "3005"
      - "5353/udp"
      - "8324"
      - "32410/udp"
      - "32412/udp"
      - "32413/udp"
      - "32414/udp"
      - "32469"
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=latest
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${POOL}/services/plex:/config
      - ${POOL}/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=http"

  # https://hub.docker.com/r/linuxserver/tautulli
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    expose:
      - "8181"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/tautulli:/config

  # https://hub.docker.com/r/linuxserver/overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    ports:
      - 5055:5055
    expose:
      - "5055"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/overseerr:/config

  # https://hub.docker.com/r/linuxserver/jellyfin
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    expose:
      - "8096"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Oslo
    volumes:
      - ${POOL}/services/jellyfin:/config
      - ${POOL}/media:/media
