version: "2.1"
services:
  # https://hub.docker.com/r/louislam/uptime-kuma
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ${POOL}/services/kuma:/app/data