- hosts: bare_metal
  tasks:
    - name: "Create test file"
      file:
        path: /tmp/test.txt
        state: touch
    - name: "Make sure test file exists"
      stat:
        path: /tmp/test.txt
      register: file_stat
    - name: "Write to test file"
      copy:
        content: "Hello, World!"
        dest: /tmp/test.txt
    - name: "Get test file contents"
      command: "cat /tmp/test.txt"
      register: test_file_contents
    - name: "Print test file contents"
      debug:
        var: test_file_contents.stdout
