[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["skarre-r <skarre-r@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
