[project]
name = "homelab"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.8.0",
    "ansible-dev-tools>=25.5.2",
    "ansible-lint>=25.6.1",
    "passlib>=1.7.4",
    "yamllint>=1.37.1",
]
