#!/usr/bin/env bash

# usage:
# bash update [SERVICE...]

docker-compose -f docker-compose.$1.yml pull
docker-compose -f docker-compose.$1.yml --project-name $1 --env-file .env up -d --remove-orphans
docker image prune -f

exit 0