---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "selfsigned-issuer"
spec:
  selfSigned: { }
---
apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "selfsigned-ca"
  namespace: "cert-manager"
spec:
  issuerRef:
    name: "selfsigned-issuer"
    kind: "ClusterIssuer"
    group: "cert-manager.io"
  secretName: "ca-cert"
  isCA: true
  commonName: "selfsigned-ca"
  subject: { }
  privateKey:
    algorithm: "ECDSA"
    size: 256
---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "ca-issuer"
spec:
  ca:
    secretName: "ca-cert"
