---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "headlamp-lb"
  namespace: "headlamp"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.55"
spec:
  type: "LoadBalancer"
  ports:
    - port: 80
      targetPort: 4466
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: "headlamp"
