---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "headlamp-admin"
  namespace: "headlamp"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "headlamp-admin"
  namespace: "headlamp"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "cluster-admin"
subjects:
  - kind: "ServiceAccount"
    name: "headlamp-admin"
    namespace: "headlamp"
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "headlamp-admin"
  namespace: "headlamp"
  annotations:
    kubernetes.io/service-account.name: "headlamp-admin"
type: "kubernetes.io/service-account-token"
