# https://github.com/rancher/local-path-provisioner
# https://www.talos.dev/v1.9/kubernetes-guides/configuration/local-storage/
# "nodePathMap": [ { "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES", "paths": ["/pool/volumes"] } ],
---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "local-path-storage"
resources:
  - "github.com/rancher/local-path-provisioner/deploy?ref=v0.0.31"
patches:
  - patch: |-
      apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        name: "local-path-config"
        namespace: "local-path-storage"
      data:
        config.json: |-
          {
            "nodePathMap": [
              { "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES", "paths": ["/pool/volumes"] }
            ]
          }
  - patch: |-
      apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        name: "local-path-config"
        namespace: "local-path-storage"
      data:
        setup: |-
          #!/bin/sh
          set -eu
          mkdir -p "$VOL_DIR"
  - patch: |-
      apiVersion: "storage.k8s.io/v1"
      kind: "StorageClass"
      metadata:
        name: "local-path"
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  - patch: |-
      apiVersion: "v1"
      kind: "Namespace"
      metadata:
        name: "local-path-storage"
        labels:
          pod-security.kubernetes.io/enforce: privileged