# TODO: rename file
---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "flux-operator"
  namespace: "flux-system"
spec:
  url: "oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "flux-operator"
  namespace: "flux-system"
spec:
  interval: "24h"
  releaseName: "flux-operator"
  chart:
    spec:
      chart: "flux-operator"
      version: "0.19.0"
      sourceRef:
        kind: "HelmRepository"
        name: "flux-operator"
  targetNamespace: "flux-system"
  values:
    installCRDs: true
