---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "prowlarr-config"
  namespace: "prowlarr"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "prowlarr-config"
  volumeMode: "Filesystem"
