---
apiVersion: v1
kind: Service
metadata:
  name: "prowlarr"
  namespace: "prowlarr"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "prowlarr"
  ports:
    - port: 9696
      targetPort: 9696
      protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: "prowlarr-lb"
  namespace: "prowlarr"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.60"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "prowlarr"
  ports:
    - port: 80
      targetPort: 9696
      protocol: "TCP"
