---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "sonarr-config"
  namespace: "sonarr"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "sonarr-config"
    namespace: "sonarr"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/sonarr"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "sonarr-media"
  namespace: "sonarr"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "sonarr-media"
    namespace: "sonarr"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/media"
