---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sonarr-config"
  namespace: "sonarr"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "sonarr-config"
  volumeMode: "Filesystem"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sonarr-media"
  namespace: "sonarr"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "sonarr-media"
  volumeMode: "Filesystem"
