---
apiVersion: v1
kind: Service
metadata:
  name: "sonarr"
  namespace: "sonarr"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "sonarr"
  ports:
    - port: 8989
      targetPort: 8989
      protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: "sonarr-lb"
  namespace: "sonarr"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.58"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "sonarr"
  ports:
    - port: 80
      targetPort: 8989
      protocol: "TCP"
