---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "jellyfin"
  namespace: "jellyfin"
  labels:
    app.kubernetes.io/name: "jellyfin"
    app.kubernetes.io/component: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "jellyfin"
      app.kubernetes.io/component: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "jellyfin"
        app.kubernetes.io/component: "server"
    spec:
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: "jellyfin-config"
        - name: "cache"
          persistentVolumeClaim:
            claimName: "jellyfin-cache"
        - name: "media"
          persistentVolumeClaim:
            claimName: "jellyfin-media"
        - name: "dri"
          hostPath:
            path: "/dev/dri"
      containers:
        - name: "jellyfin"
          image: "docker.io/jellyfin/jellyfin:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8096
              protocol: "TCP"
          startupProbe:
            tcpSocket:
              port: 8096
          readinessProbe:
            tcpSocket:
              port: 8096
          livenessProbe:
            tcpSocket:
              port: 8096
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/cache"
              name: "cache"
            - mountPath: "/media"
              name: "media"
            - mountPath: "/dev/dri"
              name: "dri"

