---
apiVersion: v1
kind: "Service"
metadata:
  name: "whoami"
  namespace: "whoami"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.50"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "whoami"
    app.kubernetes.io/component: "web-server"
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
