---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "transmission"
  namespace: "transmission"
  labels:
    app.kubernetes.io/name: "transmission"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "transmission"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "transmission"
    spec:
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: "transmission-config"
        - name: "downloads"
          persistentVolumeClaim:
            claimName: "transmission-downloads"
      containers:
        - name: "transmission"
          image: "lscr.io/linuxserver/transmission:latest"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "TZ"
              value: "Europe/Oslo"
            - name: "PUID"
              value: "1000"
            - name: "PGID"
              value: "1000"
          ports:
            - containerPort: 9091
              protocol: "TCP"
          startupProbe:
            tcpSocket:
              port: 9091
          readinessProbe:
            tcpSocket:
              port: 9091
          livenessProbe:
            tcpSocket:
              port: 9091
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/downloads"
              name: "downloads"

