---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "transmission-config"
  namespace: "transmission"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "transmission-config"
  volumeMode: "Filesystem"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "transmission-downloads"
  namespace: "transmission"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "transmission-downloads"
  volumeMode: "Filesystem"
