---
apiVersion: v1
kind: Service
metadata:
  name: "transmission"
  namespace: "transmission"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "transmission"
  ports:
    - port: 9091
      targetPort: 9091
      protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: "transmission-lb"
  namespace: "transmission"
  annotations:
    lbipam.cilium.io/ips: "192.168.1.57"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "transmission"
  ports:
    - port: 80
      targetPort: 9091
      protocol: "TCP"
