---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "prowlarr-config"
  namespace: "wireguard"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "prowlarr-config"
    namespace: "wireguard"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/prowlarr"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "transmission-config"
  namespace: "wireguard"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "transmission-config"
    namespace: "wireguard"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/transmission"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "transmission-downloads"
  namespace: "wireguard"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "transmission-downloads"
    namespace: "wireguard"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/media/downloads"  # TODO
