---
apiVersion: "cilium.io/v2"
kind: "CiliumNetworkPolicy"
metadata:
  name: "gluetun"
  namespace: "gluetun"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: "gluetun"
  egress:
    # Allow egress traffic through wireguard
    - toCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "3125"  # wireguard endpoint port
              protocol: "UDP"
    # Allow traffic to k8s DNS
    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: "UDP"
    # Allow traffic to other services in the cluster
    - toServices:
        - k8sService:
            serviceName: "radarr"
            namespace: "radarr"
        - k8sService:
            serviceName: "sonarr"
            namespace: "sonarr"
