---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "busybox"
  namespace: "default"
  labels:
    app.kubernetes.io/name: "busybox"
    app.kubernetes.io/part-of: "busybox"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "busybox"
      app.kubernetes.io/part-of: "busybox"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "busybox"
        app.kubernetes.io/part-of: "busybox"
    spec:
      containers:
        - name: "busybox"
          image: "docker.io/busybox:latest"
          imagePullPolicy: "IfNotPresent"
          command: [ "/bin/sh", "-c", "while true; do sleep 3600; done" ]
          resources: { }
          volumeMounts:
            - mountPath: "/pvc-1"
              name: "pvc-1"
            - mountPath: "/pvc-2"
              name: "pvc-2"
      volumes:
        - name: "pvc-1"
          persistentVolumeClaim:
            claimName: "busybox-lp"
        - name: "pvc-2"
          persistentVolumeClaim:
            claimName: "busybox-hp"
