---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "radarr-config"
  namespace: "radarr"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "radarr-config"
    namespace: "radarr"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/services/radarr"
---
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "radarr-media"
  namespace: "radarr"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "local-path"
  claimRef:
    apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    name: "radarr-media"
    namespace: "radarr"
  volumeMode: "Filesystem"
  capacity:
    storage: "15Ti"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/pool/media"
