---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "radarr-config"
  namespace: "radarr"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "radarr-config"
  volumeMode: "Filesystem"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "radarr-media"
  namespace: "radarr"
spec:
  storageClassName: "local-path"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "radarr-media"
  volumeMode: "Filesystem"
